Network: TANet      # RefineDet ...


# config for extracting the voxel feature with TA module
TA:

    INPUT_C_DIM: 9
    BOOST_C_DIM: 16  # or 32
    NUM_POINTS_IN_VOXEL: 60
    REDUCTION_PA: 4
    REDUCTION_CA: 4
    USE_PACA_WEIGHT: True

PSA:
    C_Bottle: 128
    C_Reudce: 32





